### ISSUE TITLE
can't find this paper 

### ISSUE THREAD

**Issue by angela000** [FengHZ/AAAI2021-260#1]
could you please open your paper link?

**Comment by FengHZ** [comment]
Our paper is still under the anonymous review stage, so we have hidden the link. We will release the pdf once after the review.

**Comment by ghost** [comment]
Our paper is still under the anonymous review stage, so we have hidden the link. We will release the pdf once after the review.

**Comment by FengHZ** [comment]
our paper has been accepted for presentation at aaai2021 with the [arxiv preprint](https://arxiv.org/abs/2011.10684).
